### ISSUE TITLE
Bug: Ошибка на главной странице

### ISSUE THREAD

**Issue by kaa-it** [CosmicTeam/react-project-kitchen-frontend#107]

**Comment by kaa-it** [comment]
![Screenshot from 2021-11-17 13-28-46](https://user-images.githubusercontent.com/4102978/142183882-478beb0a-bdd2-40b8-a239-bdfdea6860b6.png)

**Comment by SergeyK2004** [comment]
Андрей, не могу повторить ошибку. У меня окно с тэгами растягивается чтобы вместить все тэги, все корректно.
