### ISSUE TITLE
Bug: Ошибка при добавлении статьи в избранное.

### ISSUE THREAD

**Issue by kaa-it** [CosmicTeam/react-project-kitchen-frontend#26]

**Comment by kaa-it** [comment]
![2021-09-19](https://user-images.githubusercontent.com/4102978/133926498-5f58c998-84f5-4fb4-a67f-0684fd35f576.png)

**Comment by kaa-it** [comment]
Происходит при нажатии на сердечке в предварительном просмотре статьи.

**Comment by rossifumi46** [comment]
надо версию монго заменить на 3.2. Я в слаке указал. Надо еще обработку ошибок добавить на фронте.
