### ISSUE TITLE
Bug: Ошибка при просмотре избранных статей в профиле.

### ISSUE THREAD

**Issue by kaa-it** [CosmicTeam/react-project-kitchen-frontend#27]

**Comment by kaa-it** [comment]
![2021-09-19](https://user-images.githubusercontent.com/4102978/133926672-5e5f1faa-6216-4fd2-b530-5106662998b1.png)

Происходит при попытке перейти на вкладку избранное на странице профиля пользователя.

**Comment by edword03** [comment]
Тут скорее из-за редакса и то что связанно с ним через роуты
