### ISSUE TITLE
Task: Убрать стили бутстрап. Доработать верстку основной страницы и проверить все остальное.

### ISSUE THREAD

**Issue by SergeyK2004** [CosmicTeam/react-project-kitchen-frontend#93]

**Comment by kaa-it** [comment]
После выкидывания бутстрапа убедиться, что ширина содержимого баннера совпадает с шириной содержимого заголовка
![Screenshot from 2021-11-07 18-28-09](https://user-images.githubusercontent.com/4102978/140651398-077cf7b3-6a0b-442b-a476-2edc6c4617ef.png)
.

**Comment by SergeyK2004** [comment]
Да, я про это и говорил что надо доработать, и ширина не сходится с макетом и популярные тэги уезжают и высота полей Input меняется. Постараюсь по всем экранам пройтись проверить и шрифты и размеры.
